services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: mysql_rag
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123
      MYSQL_DATABASE: rag_database
      MYSQL_USER: n8n_user
      MYSQL_PASSWORD: n8n_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - rag_network
    command: --default-authentication-plugin=mysql_native_password

  # Ollama LLM Server
  ollama:
    image: ollama/ollama:latest
    container_name: ollama_server
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - rag_network
    deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: 1
                capabilities: [gpu]
      
    # Uncomment if you have NVIDIA GPU support
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

  # n8n Workflow Automation
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n_workflows
    restart: unless-stopped
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - DB_TYPE=mysqldb
      - DB_MYSQLDB_HOST=mysql
      - DB_MYSQLDB_PORT=3306
      - DB_MYSQLDB_DATABASE=rag_database
      - DB_MYSQLDB_USER=n8n_user
      - DB_MYSQLDB_PASSWORD=n8n_password
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - rag_network
    depends_on:
      - mysql
      - ollama
  postgres:
    image: postgres:15
    container_name: postgres_rag
    restart: unless-stopped
    environment:
      POSTGRES_USER: n8n_user
      POSTGRES_PASSWORD: n8n_password
      POSTGRES_DB: rag_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    networks:
      - rag_network
      
  # Optional: alternativa leggera a pgAdmin
  pgweb:
    image: sosedoff/pgweb:latest
    container_name: pgweb_rag
    restart: unless-stopped
    environment:
      DATABASE_URL: "postgres://n8n_user:n8n_password@postgres:5432/rag_database?sslmode=disable"
    ports:
      - "8081:8081"
    networks:
      - rag_network
    depends_on:
       - postgres
  # Optional: phpMyAdmin for database management
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_rag
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: rootpassword123
    ports:
      - "8080:80"
    networks:
      - rag_network
    depends_on:
      - mysql

volumes:
  mysql_data:
    driver: local
  ollama_data:
    driver: local
  n8n_data:
    driver: local
  postgres_data:
    driver: local

networks:
  rag_network:
    driver: bridge